inst = {
   'name' : 'Clickbait',
   'experimental' : {
      'danger' : set([
                  "HIV",
                  "AIDS",
                  "Cancer",
                  "Syphillis",
                  "September_11_attacks",
                  "Myocardial_infarction",
                  "Terrorist_attack",
                  "Columbine_High_School_massacre",
                  "Sandy_Hook_Elementary_School_shooting" , 
                  "Ebola_virus_disease" , 
                  "Typhoid_fever" , 
                  "Rabies" , 
                  "HIV/AIDS" , 
                  "Anthrax#Pulmonary" , 
                  "Herpes_B_virus" , 
                  "Anthrax#Gastrointestinal" , 
                  "Reye_syndrome" , 
                  "Yellow_fever" , 
                  "Severe_acute_respiratory_syndrome" , 
                  "Botulism" , 
                  "Hepatitis_A" , 
                  "Cerebrovascular_disease" , 
                  "Respiratory_tract_infection" , 
                  "Pneumonia" , 
                  "Respiratory_disease" , 
                  "Traffic_collision" , 
                  "Cirrhosis" , 
                  "Uterine_cancer" , 
                  "Hepatitis_B" , 
                  "Epilepsy" , 
                  "Ovarian_cancer" , 
                  "Bladder_cancer" , 
                  "Sexually_transmitted_infection" , 
                  "Parasitism" , 
                  "Gonorrhea" , 
                  "Chlamydia_infection" , 
                  "Urethritis" , 
                  "Genital_wart" , 
                  "Human_papillomavirus" , 
                  "Meningitis" , 
                  "Pathogen" , 
                  "Endemic_(epidemiology)" , 
                  "Dysentery" , 
                  "Apocalypse" , 
                  "Tropical_cyclone" , 
                  "Tornado" , 
                  "Earthquake" , 
                  "Explosion" , 
                  "Death_by_burning" , 
                  "Serial_killer" , 
                  "Death" , 
                  "Starvation" , 
                  "Famine" , 
                  "Cardiac_arrest" , 
                  "End_time" , 
                  "Death_by_boiling" , 
                  "Disembowelment" , 
                  "Drowning#Capital_punishment" , 
                  "Asphyxia" , 
                  "Choking" , 
                  "Genocide" , 
                  "Neurotoxin" , 
                  "Cardiotoxicity" , 
                  "Land_mine" , 
                  "Improvised_explosive_device" , 
                

                 ]),
      'sexual' : set([
                   "Sex_positions",
                   "Sexual_penetration",
                   "Blow_job",
                   "Cunnilingus",
                   "Balloon_fetish",
                   "Casual_sex",
                   "Ejaculation",
                   "Fuck",
                   "Hickey",
                   "Mechanics_of_sex",
                   "Pornography",
                   "Prostitution",
                   "Sexting",
                   "cock",
                   "Vibrator_(sex_toy)",
                   "Sexual_intercourse",
                   "Baseball_metaphors_for_sex",
                   "Sex_position",
                   "Masturbation",
                   "Doggy_style",
                   "Orgasm_control",
                   "Dildo",
                   "Strap-on_dildo",
                   "Clitorus",
                   "Handjob",
                   "Missionary_position",
                   "Oral_sex",
                   "Sexual_network",
                   "Sexual_revolution",
                   "Sexual_roleplay",
                   "Strip_poker",
                   "Wax_play",
                   "heterosexuality",
                   "homosexuality",
                   "Anal_sex",
                   "Condom",
                   "Oral_sex" , 
                   "Facesitting" , 
                   "69_(sex_position)" , 
                   "Fingering_(sexual_act)" , 
                   "Foreplay" , 
                   "Pearl_necklace_(sexuality)" , 
                   "Cum_shot" , 
                   "Creampie_(sexual_act)" , 
                   "Deep-throating" , 
                   "Teabagging" , 
                   "Doggy_style" , 
                   "Lap_dance" , 
                   "Stripper" , 
                   "Striptease" , 
                   "Group_sex" ,
                   "Threesome" ,
                   "Circle_jerk_(sexual_practice)" 
                 ]),
      'political' : set([
                    "Al-Qaeda",
                    "Patriot_Act",
                    "Roe_v._Wade",
                    "George_W._Bush",
                    "Gay_marriage",
                    "Socialism",
                    "World_government",
                    "Affirmative_action",
                    "Pro-life",
                    "Zionism",
                    "Arab-Israeli_conflict",
                    "American_Civil_Liberties_Union",
                    "Abortion",
                    "Legalization_of_drugs",
                 "Sexual_orientation_and_the_United_States_military",
                    "Iraq_War",
                    "Barack_Obama",
                    "Islamic_State_of_Iraq_and_the_Levant"
                    "Left-wing_politics" , 
                    "Ultra-leftism" , 
                    "Far-right_politics" , 
                    "Right-wing_politics" , 
                    "Socialist_feminism" , 
                    "Trotskyism" , 
                    "Stem_cell" , 
                    "Separation_of_church_and_state" , 
                    "Karl_Marx" , 
                    "Marxian_economics" , 
                    "Trade_union" , 
                    "Asset-based_egalitarianism" , 
                    "Anarchism" , 
                    "Communism" , 
                    "Socialism" , 
                    "Feminist_movement" , 
                    "Conservatism_in_the_United_States" 
                    "National_Association_for_the_Advancement_of_Colored_People" , 
                    "Social_democracy" , 
                    "Right-wing_populism" , 
                    "The_Communist_Manifesto" , 
                    "Economic_liberalism" , 
                    "Ronald_Reagan" , 
                    "Libertarian_conservatism" , 
                    "Fascism" , 
                    "Eco-socialism" , 
                    "Democratic_Party_(United_States)" , 
                    "Jimmy_Carter" , 
                    "Watergate_scandal" , 
                    "Assault_Weapons_Ban_of_2013" , 
                    "National_Rifle_Association" , 
                    "Supply-side_economics" , 
                    "Reaganomics" , 
                    "War_on_Drugs" , 
                    "Office_of_National_Drug_Control_Policy" , 
                    "Race_and_the_War_on_Drugs" , 
                    "Anti-Drug_Abuse_Act_of_1986" , 
                    "Congressional_Black_Caucus" , 
                    "Congressional_caucus" , 
                    "Congressional_Hispanic_Conference" , 
                    "Ralph_Nader" , 
                    "Mandatory_sentencing" , 
                    "Statistics_of_incarcerated_African-American_males" , 
                    "Electoral_College_(United_States)" , 
                    "Christian_right" , 
                    "Swing_state" , 
                    "United_States_congressional_apportionment" , 
                    "Republican_Party_(United_States)" , 
                    "Modern_liberalism_in_the_United_States" ,
                    "Republican_National_Committee" , 
                    "National_Republican_Congressional_Committee" , 
                    "National_Republican_Senatorial_Committee" , 
                    "Republican_Governors_Association" , 
                    "Chris_Christie" , 
                    "Libertarian_Republican" , 
                    "Classical_liberalism" , 
                    "Progressivism_in_the_United_States" , 
                    "American_Family_Association" , 
                    "Fiscal_conservatism" , 
                    "Small_government" , 
                    "Social_conservatism_in_the_United_States" , 
                    "Omnibus_spending_bill" , 
                    "Pork_barrel" , 
                    "Internal_Revenue_Code" , 
                    "Tea_Party_movement" , 
                    "United_States_Environmental_Protection_Agency" , 
                    "Federalism#United_States" , 
                    "Detainee_Treatment_Act" , 
                    "Pledge_Protection_Act" , 
                    "Marriage_Protection_Act" , 
                    "New_Deal_coalition" , 
                    "Socialized_medicine" , 
                    "Single-payer_health_care" , 
                    "Inheritance_tax" , 
                    "Patient_Protection_and_Affordable_Care_Act" , 
                    "Workers%27_compensation" , 
                    "Green_Party_of_the_United_States" , 
                    "Justice_Party_(United_States)" , 
                    "Welfare_state" , 
                    "Free_rider_problem" , 
                

                
                    ]),
      'drugs' : set([
                    "Cocaine",
                    "Marijuana",
                    "Heroine",
                    "MDMA",
                    "LSD",
                    "DMT",
                    "Oxycodone",
                    "Amphetamine",
                    "Viagra",
                    "Xanax",
                    "Alcohol", 
                    "Crack_cocaine" , 
                    "Adderall" , 
                    "Psilocybin_mushroom" , 
                    "Diazepam" , 
                    "Tadalafil" , 
                    "Buprenorphine" , 
                    "Lisdexamfetamine" , 
                    "Phenobarbital" , 
                    "Lorazepam" , 
                    "Clonazepam" , 
                    "Tramadol" , 
                    "Ketamine" , 
                    "Hydrocodone" , 
                    "Morphine" , 
                    "Anabolic_steroid" , 
                    "Oxymorphone" , 
                    "Peyote" , 
                    "Tetrahydrocannabinol" , 
                    "Methaqualone" , 
                    "Gamma-Hydroxybutyric_acid" , 
                    "Methylphenidate" , 
                    "Methamphetamine" , 
                    "Salvia_divinorum" , 
                    "Bong" , 
                    "Water_pipe_percolator" , 
                    "Vaporizer_(inhalation_device)" , 
                    "Cannabinoid" , 
                    "Synthetic_cannabis" , 
                    "Drug_paraphernalia" , 
                    "Joint_(cannabis)" , 
                    "Head_shop" , 
                    "Gravity_bong" , 
                    "Hashish" , 
                    "Hash_oil" , 
                    "Tincture_of_cannabis" , 
                    "Cannabis_foods" , 
                    "Kush_(Cannabis)" , 
                    "White_Widow_(cannabis)" , 
                    "Purple_Haze_(cannabis)" , 
                    "Cannabis_(drug)#Skunk" , 
                    "Cannabis_smoking" , 
                    "Psychoactive_drug" , 
                    "Mescaline" , 
                    "Nitrous_oxide" , 
                    "Cannabidiol" , 
                    "Cannabinol" , 
                    "Dextromethorphan" , 
                    "Phencyclidine" , 
                    "Codeine" , 
                    "Ibogaine" , 
                    "Contact_high" , 
                    "Zombie_dust_(narcotic)" , 
                    



          ])
   },
   'control' : {
       'scientific-jargon' : set([ #the idea is this is not at all clickbait.
          "BLAST",
          "Primary_structure",
          "Planck_constant",
          "Electronvolt",
          "Mitosis",
          "Chromosome",
          "Atomic_mass_unit",
          "Adiabatic_invariant",
          "Ultraviolet_catastrophe",
          "Rydberg_constant",
          "Fine-structure_constant",
          "Vacuum_permittivity",
          "Adenine",
          "Farad",
          "Adenosine_triphosphate",
          "Tautomer",
          "Glutamine",
          "Ribose" , 
          "Frequency-resolved_optical_gating" , 
          "Spinplasmonics" , 
          "Spinplasmonics" , 
          "Nanoarchitectonics" , 
          "Polymerization" , 
          "Polymer" , 
          "Steric_effects" , 
          "Ion" , 
          "Catenane" , 
          "Mechanically_interlocked_molecular_architectures" , 
          "Macrocycle" , 
          "Hydrogen_bond" , 
          "Hydride" , 
          "Pseudohalogen" , 
          "Boranes" , 
          "Hydrogenation" , 
          "Hydroformylation" , 
          "Hydrodesulfurization" , 
          "Octane_rating" , 
          "Alkene" , 
          "Microfluidics" , 
          "Nanometre" , 
          "Micrometre" , 
          "Viscosity" , 
          "Quantum_dot" , 
          "Thermodynamics" , 
          "Alkene" , 
          "Carbonyl" , 
          "Exciton" , 
          "Magnon" , 
          "Roton" , 
          "Plasmon" , 
          "Phonon" , 
          "Quasiparticle" , 
          "Chionodoxa" ,
          

       ])
   }
}
