inst = {
    'name' : 'hierarchical',
    'experimental' : {
        'person' : set([
            "Richard_D_James",
            "Phish",
            "Michael_Jackson",
            "Jack_Nicholson" , 
            "Stephen_King" ,
            "Stanley_Kubrick" , 
            "Adam_Sandler" , 
            "Sean_Connery" , 
            "James_Franco" , 
            "Ernest_Hemingway" , 
            "Bryan_Cranston" , 
            "Whitney_Houston" , 
            "Green_Day" , 
            "Ramones" , 
            "Al_Pacino" , 
            "Snoop_Dogg" , 
            "AC/DC" , 
            "Elvis_Presley" ,
            "Prince_(musician)" , 
            "Frank_Capra" , 
            "Clint_Eastwood" , 
            "Steven_Spielberg" , 
            "James_Cameron" , 
            "Michael_Bay" , 
            "Alice_in_Chains" , 
            "Alien_Ant_Farm" , 
            "CKY_(band)" , 
            "Flyleaf_(band)" , 
            "Incubus_(band)" , 
            "P.O.D." , 
            "Slipknot_(band)" , 
            "White_Zombie_(band)" , 
            "The_Beatles" , 
            "Talking_Heads" , 
            "The_Smiths" , 
            "Black_Sabbath" , 
            "Puddle_of_Mudd" , 
            "Rise_Against" , 
            "The_Monkees" , 
            "Donald_Sutherland" , 
            "Anthony_Hopkins" , 
            "The_Smashing_Pumpkins" , 
            "Ben_Affleck" , 
            "Spike_Lee" , 
            "The_Strokes" , 
            "Elvis_Costello" , 
            "The_Roots" , 
            "John_Legend" , 
            "Katherine_Paterson" , 
            "Leo_Tolstoy" , 
            "Oliver_Hardy" , 
            "Shirley_Temple" , 
            "John_Denver" , 
            "Robert_Downey,_Jr." , 
            "Marlon_Brando" , 
           
            

            




        ])
    },
    'control' : {
        '*ography' : set([
            "Richard_D_James_discography",
            "Michael_Jackson_albums_discography",
            "Jack_Nicholson_filmography" 
            "Stephen_King_bibliography" , 
            "Filmography_and_awards_of_Stanley_Kubrick" , 
            "Adam_Sandler_filmography" , 
            "Sean_Connery_filmography" , 
            "James_Franco_filmography" , 
            "Ernest_Hemingway_bibliography" , 
            "Bryan_Cranston_filmography" , 
            "Whitney_Houston_discography" , 
            "Whitney_Houston_videography" , 
            "Green_Day_discography" , 
            "Ramones_discography" , 
            "Al_Pacino_filmography" , 
            "Snoop_Dogg_discography" , 
            "AC/DC_discography" , 
            "Elvis_Presley_albums_discography" , 
            "Prince_albums_discography", 
            "Frank_Capra_filmography" , 
            "Clint_Eastwood_filmography" , 
            "Steven_Spielberg_filmography" , 
            "James_Cameron_filmography" , 
            "Michael_Bay_filmography" , 
            "Alice_in_Chains_discography" , 
            "Alien_Ant_Farm_discography" , 
            "CKY_discography" , 
            "Flyleaf_discography" , 
            "Incubus_discography" , 
            "P.O.D._discography" , 
            "Slipknot_discography" , 
            "White_Zombie_discography" , 
            "The_Beatles_discography" , 
            "Talking_Heads_discography" , 
            "The_Smiths_discography" , 
            "Black_Sabbath_discography" , 
            "Puddle_of_Mudd_discography" , 
            "Rise_Against_discography" , 
            "The_Monkees_discography" , 
            "Donald_Sutherland_filmography" , 
            "Anthony_Hopkins_filmography" , 
            "The_Smashing_Pumpkins_discography" , 
            "Ben_Affleck_filmography" , 
            "Spike_Lee_filmography" , 
            "The_Strokes_discography" , 
            "Elvis_Costello_discography" , 
            "The_Roots_discography" , 
            "John_Legend_discography" , 
            "Katherine_Paterson_bibliography" , 
            "Leo_Tolstoy_bibliography" , 
            "Oliver_Hardy_filmography" , 
            "Shirley_Temple_filmography" , 
            "John_Denver_discography" , 
            "Robert_Downey_Jr._filmography" , 
            "Marlon_Brando_filmography" , 
                

            
        ])
    }
}
