inst = { 
   'name' : "Microsoft_Bing", 
   'experimental' : 
   { 'microsoft' : set([
      "Microsoft_Windows",
      "Microsoft_Excel",
      "Microsoft_PowerPoint",
      "Microsoft_Office",
      "Microsoft_Silverlight",
      "Windows_Media_Player",
      "MSN",
      "Microsoft_Visual_Studio",
      "Microsoft_SQL_Server",
      "Microsoft_Developer_Network",
      "Microsoft_Exchange_Server",
      "Microsoft_TechNet",
      "Outlook.com",
      "Azure_Services_Platform",
      "Windows_98",
      "Windows_95",
      "MS-DOS",
      "Windows_Vista",
      "Windows_XP",
      "Windows_7",
      "Windows_8",
      "Windows_NT",
      "Microsoft_Outlook",
      "Windows_API",
      "Bill_Gates",
      "Windows_Live",
      "OneDrive",
      "Microsoft",
      "Bing",
      "Microsoft_Surface",
      "Kinect",
      "Xbox",
      "Xbox_360"])
   },
   'control' : {
      "technical" : set(["Linux",
      "FreeBSD",
      "OpenBSD",
      "Operating_system",
      "Matplotlib",
      "MATLAB",
      "OS_X",
      "Intel",
      "Compiler",
      "TCP",
      "Http"]),
      "companies" : set([
       "NBC",
       "Apple",
       "Netflix",
       "Comcast",
       "United_Fruit",
       "Walmart"
      ])
   }
}
