inst = {
   'name' : 'noun types',
   'experimental' : {
       'people' : {
            "Alexander_The_Great.",
            "David_Foster_Wallace",
            "Sylvia_Plath",
            "Hillary_Clinton",
            "Tupac_Shakur",
            "Cleopatra",
            "Barak_Obama",
            "David_Lynch",
            "Pablo_Escobar",
            "John_Legend",
            "Roman_Pulaski",
            "David_Hockney",
            "Chinua_Achebe",
            "Patti_Smith"
            "50_cent",
            "Steven_Pinker",
            "Jerry_Seinfeld",
            "Marie_Curie",
            "Barak_Obama",
            "Thomas_Jefferson",
            "Martin_Luther King",
            "J.K_Rowling",
            "Muhammed_Ali",
            "Mao_ZeDong",
            "Marvin_Misky",
            "George_Washington",
            "Ben_Franklin",
            "Assata_Shakur",
            "Richard_Nixon",
            "Bayard_Rustin",
            "Gabriel_Garcia Marquez",
            "Freeman_Dyson",
            "Freddie_Mercury",
            "Roger_Williams",
            "Jorge_Louis Borges"},
       'concepts' : {
            "determinism",
            "democracy",
            "paternalism",
            "Natural_number",
            "Polynomial",
            "Platonic_love",
            "Libertarianism",
            "Torque",
            "Functionalism",
            "Theory_of_mind",
            "Mean",
            "Postmodernism",
            "Exclusive_or",
            "Equal_opportunity"
            },
       'objects' : {
            "Samosa",
            "Nut_(hardware)",
            "Egg_white",
            "Axon",
            "HTTP_cookie",
            "Theramin",
            "Agent_Orange",
            "Noodle",
            "Sperm",
            "Maple_syrup",
            "Microphone",
            "Cotton",
            "Sardine",
            "Table" , 
            "Chair" , 
            "Car_seat" ,
            "Helicopter" , 
            "Train" , 
            "Hat" , 
            "Bottle" , 
            "Tank" , 
            "Bed" , 
            "Mobile_phone" , 
            "Calculator" , 
            "Bass_guitar" , 
            "Bicycle"
            }, 
       'events' : {
            "alamo",
            "stanley cup",
            "world series",
            "Columbia Exhibit",
            "Christmas",
            "French_revolution" ,
            "Super_Bowl" , 
            "Ramadan" , 
            "X_Games" , 
            "Firefly_Music_Festival" , 
            "New_Year%27s_Eve" , 
            "Battle_of_the_Bulge" , 
            "Battle_of_Gettysburg" ,
            "East_Coast_Surfing_Championships" , 
            "Los_Angeles_Fashion_Week" , 
            "Men%27s_Fashion_Week" , 
            "Mercedes-Benz_Fashion_Week_Miami" , 
            "Woodstock" , 
            "New_Year%27s_Day_Parade" , 
            "Ideal_Home_Show" , 
            "Boston_Tea_Party" , 
            "Battle_of_Bunker_Hill" , 
            "Siege_of_Boston" , 
            "Boston_Early_Music_Festival" , 
            "International_Storytelling_Championship" , 
            "National_Storytelling_Festival" , 
            "StorySLAM"
            }
   },
   'control' : {
 
       }
}
